services:
    buyrequest.api:
        container_name: Buyrequest.Api
        image: ${DOCKER_REGISTRY-}buyrequestapi
        build:
            context: .
            dockerfile: BuyRequest/BuyRequest.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ASPNETCORE_URL=http://+"
        ports:
            - 8011:80
            - 8012:443

    cashbook.api:
        container_name: Cashbook.Api
        image: ${DOCKER_REGISTRY-}cashbookapi
        build:
            context: .
            dockerfile: CashBook/CashBook.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ASPNETCORE_URL=http://+"
        ports:
            - 8021:80
            - 8022:443
        depends_on:
            - cashbook.ApiClient

    document.api:
        container_name: Document.Api
        image: ${DOCKER_REGISTRY-}documentapi
        build:
            context: .
            dockerfile: Document/Document.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ASPNETCORE_URL=http://+"
        ports:
            - 8031:80
            - 8032:443

    product.api:
        container_name: Product.Api
        image: ${DOCKER_REGISTRY-}productapi
        build:
            context: .
            dockerfile: Product/Product.Api/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ASPNETCORE_URL=http://+"
        ports:
            - 8041:80
            - 8042:443

    cashbook.ApiClient:
        image: rabbitmq:3-management
        container_name: Cashbook.ApiClient
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 15672:15672
            - 5672:5672
