version: "3"
services:
  cashbook:
    container_name: cashbook
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 6020:80